# Generated by Django 3.0.3 on 2020-03-20 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calibr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibr_name', models.CharField(max_length=30, verbose_name='Калибр')),
                ('value_calibr', models.FloatField()),
            ],
            options={
                'verbose_name': 'Калибр',
                'verbose_name_plural': 'Калибры',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=30, verbose_name='название оборудования')),
                ('group_weight', models.BooleanField()),
                ('this_is_sdl', models.BooleanField()),
                ('type_equipment', models.CharField(choices=[('Cig', 'Измеряет сигареты'), ('Filter', 'Измеряет фильтра')], max_length=6, verbose_name='Тип измерений')),
                ('place_equipment', models.CharField(choices=[('First', 'Первый день'), ('Second', 'Второй день')], max_length=30, verbose_name='Калибровочный день')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True)),
                ('size_one', models.FloatField(blank=True)),
                ('size_two', models.FloatField(blank=True)),
                ('airPD', models.IntegerField(blank=True)),
                ('airVent', models.FloatField(blank=True)),
                ('data_messure', models.DateField()),
                ('time_messure', models.TimeField()),
                ('name_user', models.CharField(max_length=30)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qmedata.Equipment')),
            ],
            options={
                'verbose_name': 'Измерение',
                'verbose_name_plural': 'Измерения',
            },
        ),
    ]
