# Generated by Django 3.0.3 on 2020-03-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_name',
            field=models.CharField(max_length=30, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='airPD',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='calibr',
            unique_together={('calibr_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='equipment',
            unique_together={('equipment_name',)},
        ),
    ]
