# Generated by Django 3.0.3 on 2020-03-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmedata', '0002_auto_20200322_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='airVent',
            field=models.FloatField(null=True),
        ),
    ]
