# Generated by Django 3.0.3 on 2020-03-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmedata', '0003_auto_20200322_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='airPD',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='airVent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='size_two',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
