# Generated by Django 3.0.3 on 2020-03-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmedata', '0007_auto_20200324_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deviations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_ind_weight', models.FloatField(default=0.005)),
                ('dev_grp_weight', models.FloatField(default=0.009)),
            ],
        ),
    ]
